// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPHv8VksX5876s0GvXCoFo4sB5uzABDNQ',
    appId: '1:638039091182:web:bd3388b4dd29416cfd10ff',
    messagingSenderId: '638039091182',
    projectId: 'mynotes-flutter-d6abd',
    authDomain: 'mynotes-flutter-d6abd.firebaseapp.com',
    storageBucket: 'mynotes-flutter-d6abd.firebasestorage.app',
    measurementId: 'G-M42NFHT4E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVINCyWbLsNuk3MvtE8KcdZ5P9piTrHcc',
    appId: '1:638039091182:android:8735c3dc62da0d82fd10ff',
    messagingSenderId: '638039091182',
    projectId: 'mynotes-flutter-d6abd',
    storageBucket: 'mynotes-flutter-d6abd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGFdK1OTTIvIuhXbgjlWezqGGmtMoNpPE',
    appId: '1:638039091182:ios:77af7828f4a43dfafd10ff',
    messagingSenderId: '638039091182',
    projectId: 'mynotes-flutter-d6abd',
    storageBucket: 'mynotes-flutter-d6abd.firebasestorage.app',
    iosBundleId: 'xyz.tinderdev.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGFdK1OTTIvIuhXbgjlWezqGGmtMoNpPE',
    appId: '1:638039091182:ios:77af7828f4a43dfafd10ff',
    messagingSenderId: '638039091182',
    projectId: 'mynotes-flutter-d6abd',
    storageBucket: 'mynotes-flutter-d6abd.firebasestorage.app',
    iosBundleId: 'xyz.tinderdev.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPHv8VksX5876s0GvXCoFo4sB5uzABDNQ',
    appId: '1:638039091182:web:8a267ab403eccdc9fd10ff',
    messagingSenderId: '638039091182',
    projectId: 'mynotes-flutter-d6abd',
    authDomain: 'mynotes-flutter-d6abd.firebaseapp.com',
    storageBucket: 'mynotes-flutter-d6abd.firebasestorage.app',
    measurementId: 'G-5W4HC8QHYY',
  );
}
